import Link from "next/link";
import Image from "next/image";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-cyber-bg flex flex-col">
      <nav className="border-b border-cyber-border bg-cyber-bg/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5 group">
            <Image src="/logo.png" alt="VulnAI" width={36} height={36} className="rounded-lg" />
            <span className="text-xl font-bold"><span className="text-white">Vuln</span><span className="text-cyber-cyan">AI</span></span>
          </Link>
          <Link href="/" className="text-sm font-semibold text-cyber-muted hover:text-cyber-cyan transition-colors">
            Back to Home
          </Link>
        </div>
      </nav>

      <main className="flex-grow px-6 py-16">
        <div className="mx-auto max-w-4xl bg-cyber-card border border-cyber-border rounded-xl p-8 md:p-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyber-cyan/30 bg-cyber-cyan/10 px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-cyber-cyan mb-6">
            Legal Document
          </div>
          <h1 className="text-3xl md:text-5xl font-bold text-white mb-6">Privacy Policy</h1>
          <p className="text-sm text-cyber-muted mb-12">Last Updated: April 2026</p>

          <div className="space-y-8 text-cyber-muted leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-white mb-4">1. Information We Collect</h2>
              <p>When you use VulnAI, we may collect information about you, including:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Account Information (Email address, password hashes).</li>
                <li>Security Scan Output (Raw scan data provided by you, temporarily stored during processing).</li>
                <li>Generated Reports (PDFs and structured data generated by our AI).</li>
                <li>Usage Data (IP addresses, browser types, timestamp, and activity logs).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-4">2. How We Use Your Information</h2>
              <p>We use the information we collect to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Provide, maintain, and improve our services.</li>
                <li>Generate penetration testing reports via AI.</li>
                <li>Process payments and manage billing (via Paystack).</li>
                <li>Send security alerts, OTPs, and support messages.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-4">3. Data Security & Encryption</h2>
              <p>Security is our core business. We implement robust measures to protect your data:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>All generated reports are stored using AES-256-CBC encryption at rest.</li>
                <li>We do not train our public AI models on your private scan data.</li>
                <li>All data transit occurs over TLS 1.3 encrypted connections.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-4">4. Contact Us</h2>
              <p>If you have any questions about this Privacy Policy, please contact us at <a href="mailto:privacy@vulnai.com" className="text-cyber-cyan hover:underline">privacy@vulnai.com</a>.</p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
