import Link from "next/link";
import Image from "next/image";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-cyber-bg flex flex-col">
      <nav className="border-b border-cyber-border bg-cyber-bg/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5 group">
            <Image src="/logo.png" alt="VulnAI" width={36} height={36} className="rounded-lg" />
            <span className="text-xl font-bold"><span className="text-white">Vuln</span><span className="text-cyber-cyan">AI</span></span>
          </Link>
          <Link href="/" className="text-sm font-semibold text-cyber-muted hover:text-cyber-cyan transition-colors">
            Back to Home
          </Link>
        </div>
      </nav>

      <main className="flex-grow px-6 py-16">
        <div className="mx-auto max-w-4xl bg-cyber-card border border-cyber-border rounded-xl p-8 md:p-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyber-cyan/30 bg-cyber-cyan/10 px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-cyber-cyan mb-6">
            Legal Document
          </div>
          <h1 className="text-3xl md:text-5xl font-bold text-white mb-6">Terms of Service</h1>
          <p className="text-sm text-cyber-muted mb-12">Last Updated: April 2026</p>

          <div className="space-y-8 text-cyber-muted leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
              <p>By accessing or using VulnAI, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-4">2. Description of Service</h2>
              <p>VulnAI provides an AI-powered platform that converts raw security scanner output into formatted, human-readable penetration testing reports. The Service is provided "as is" and is intended to assist, not replace, human security analysts.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-4">3. Authorized Use & Legal Scanning</h2>
              <p>You agree to only use VulnAI to process scan data from networks, systems, and applications that you own or have explicit, documented authorization to test. You must not use our service to process data obtained illegally.</p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold text-white mb-4">4. Limitation of Liability</h2>
              <p>VulnAI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service or reliance on the generated reports. Security findings generated by AI may contain inaccuracies and should be manually verified.</p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
