import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

export async function generateVulnReport(
  scanInput: string,
  scanType: string
): Promise<string> {
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const systemPrompt = `You are a CREST-certified senior penetration tester and cybersecurity consultant with 15 years of experience writing formal vulnerability assessment reports for enterprise clients. You are working in 2026. You write technically precise, professionally formatted security reports. You never make up vulnerabilities that are not implied by the scan data. If the input is minimal, you still generate the best report possible from what is available.`;

  const userPrompt = `Analyze the following ${scanType} scan output and generate a complete, professional vulnerability assessment report.

SCAN DATA:
\`\`\`
${scanInput}
\`\`\`

Generate the report using EXACTLY this markdown structure:

# Vulnerability Assessment Report

## 1. Executive Summary
(2-3 sentences for non-technical stakeholders about overall risk posture)

## 2. Scan Metadata
- **Tool Used:** ${scanType}
- **Scan Date:** ${currentDate}
- **Targets Identified:** [extract from input]
- **Total Findings:** [count]

## 3. Vulnerability Findings
(For EACH vulnerability found, repeat this block:)

### [Full Vulnerability Name]
- **Severity:** 🔴 CRITICAL | 🟠 HIGH | 🟡 MEDIUM | 🟢 LOW | ℹ️ INFO
- **CVE Reference:** CVE-XXXX-XXXXX (if known, otherwise "N/A")
- **Affected Component:** [port/service/version]
- **Description:** [technical explanation]
- **Risk Impact:** [what an attacker could do]
- **Evidence:** [exact line from scan that reveals this]
- **Remediation:** [specific fix with version numbers where possible]
- **Priority:** Immediate | Short-term | Long-term

## 4. Risk Summary Table
| Severity | Count | Risk Level |
|---|---|---|
| 🔴 Critical | X | Immediate Action |
| 🟠 High | X | Fix within 7 days |
| 🟡 Medium | X | Fix within 30 days |
| 🟢 Low | X | Fix within 90 days |
| ℹ️ Informational | X | Monitor |

## 5. Top 5 Remediation Priorities
(Numbered list, most critical first, with specific actionable steps)

## 6. Conclusion
(2-3 sentences summarizing overall posture and recommended next steps)

---
*Report generated by VulnAI · Powered by Gemini AI · 2026*

IMPORTANT RULES:
- Only report vulnerabilities that are genuinely implied by the scan data
- Use real CVE numbers when the vulnerability is well-known (e.g., vsftpd 2.3.4 backdoor = CVE-2011-2523)
- Be specific in remediation steps (include exact version numbers to upgrade to)
- Use the severity emoji indicators exactly as shown above
- Maintain professional, client-facing tone throughout
- Do NOT wrap the entire output in a code block — output raw markdown directly`;

  const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-lite",
    contents: fullPrompt,
  });

  const text = response.text;

  if (!text || text.trim().length === 0) {
    throw new Error("Empty response from AI. Please try again.");
  }

  return text;
}
